---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(stringr)
```

```{r}
all_protocols <- read_csv('protocols.csv',col_names = 'protocol_id')%>%
  mutate(protocol_id = str_trim(protocol_id)) 
```


```{r final_table}
protocols_subset <- 
  read.delim('Protocol-list-201703.txt',
             col.names = c("num_id",
                           "name",
                           "institute",
                           "description",
                           "protocol_id"),
             sep = "|") %>% 
  mutate(protocol_id = str_trim(protocol_id),
         prot_category = str_extract(protocol_id, "[A-Z]{1,2}")) %>% 
  group_by(protocol_id) %>% 
  summarise_all(first) 

  

n_m <- protocols_subset %>% 
filter(str_detect(prot_category, "^N$|^M$")) %>% 
  arrange(prot_category)

not_n_m <- protocols_subset %>% 
filter(!str_detect(prot_category, "^N$|^M$")) %>% 
  arrange(prot_category)

reorganized <- bind_rows(n_m, not_n_m) %>% transmute(Name =name, Protocol = protocol_id, Description = description) 
reorganized %>% write_csv(path = ('output.csv'))
# duplicates <- protocols_subset %>% count(protocol_id) %>% filter(n>1)
# protocols_subset %>% right_join(duplicates) %>% View


  
```


```{r other_protocol_ids}
  superset_specific <- 
    all_protocols %>%
    left_join(protocols_subset) %>% 
    filter(is.na(institute)) %>% 
    select(protocol_id) %>% 
  mutate(prot_category = str_extract(protocol_id, "[A-Z]{1,2}"))
    
    
n_and_m_ss <- superset_specific %>%
  filter(str_detect(prot_category, "^N$|^M$")) %>% 
  arrange(prot_category)

not_n_and_m_ss <- superset_specific %>%
  filter(!str_detect(prot_category, "^N$|^M$")) %>% 
  arrange(prot_category)
```
```{r write_output_for_other_protocols}
n_and_m_ss %>% write_csv('unaccounted_n_and_m.csv')
not_n_and_m_ss %>% write_csv('unaccounted_others.csv')
```


